version: "3.2"
services:
  redis:
    image: redis:alpine
    ports:
      - "6378:6379"

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stocks
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stocks
